CREATE TABLE CINEMA(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    WORKDAY_START_HOURS TIME NOT NULL,
    WORKDAY_END_HOURS TIME NOT NULL,
    WEEKEND_START_HOURS TIME NOT NULL,
    WEEKEND_END_HOURS TIME NOT NULL

);

CREATE SEQUENCE CINEMA_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

CREATE TABLE HALL(
    ID BIGINT PRIMARY KEY,
    SEATS VARCHAR(255) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    IS_AVAILABLE BOOL DEFAULT TRUE NOT NULL,
    CINEMA_ID BIGINT REFERENCES CINEMA (ID) NOT NULL
);
CREATE SEQUENCE HALL_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

CREATE TABLE MOVIE(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(128) NOT NULL,
    AGE_LIMIT SMALLINT DEFAULT 0 NOT NULL,
    DURATION_IN_SEC BIGINT NOT NULL,
    DIRECTOR VARCHAR(64) NOT NULL,
    ORIGINAL_LANGUAGE VARCHAR(64),
    PRODUCTION_YEAR SMALLINT NOT NULL,
    PRODUCTION_COUNTRY VARCHAR(64) NOT NULL,
    IS_ACTIVE BOOL DEFAULT TRUE NOT NULL
);

CREATE SEQUENCE MOVIE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;


CREATE TABLE SHOW(
    ID BIGINT PRIMARY KEY,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    HALL_ID BIGINT REFERENCES HALL (ID) NOT NULL,
    MOVIE_ID BIGINT REFERENCES MOVIE (ID) NOT NULL
);

CREATE SEQUENCE SHOW_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

CREATE TABLE BOOKING(
    ID BIGINT PRIMARY KEY,
    CLIENT_EMAIL VARCHAR(64) NOT NULL,
    SEATS VARCHAR(128) NOT NULL,
    SHOW_ID BIGINT REFERENCES SHOW (ID) NOT NULL,
    IS_ACTIVE BOOL NOT NULL DEFAULT TRUE
);

CREATE SEQUENCE BOOKING_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE;

